name: 🤖 MCP Integration Pipeline

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'MCP test mode'
        required: false
        default: 'full'
        type: choice
        options:
          - full
          - quick
          - codegen_only
          - validation_only
  
  push:
    branches: [ main ]
    paths:
      - 'automation_framework/mcp_integration.py'
      - 'automation_framework/playwright_mcp_runner.py'

env:
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '18'

jobs:
  mcp_server_health:
    name: 🔍 MCP Server Health Check
    runs-on: ubuntu-latest
    
    steps:
      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: 🎭 Install Playwright MCP Server
        run: |
          npm install -g @executeautomation/playwright-mcp-server
          npx playwright install chromium
      
      - name: 🔍 Health Check
        run: |
          echo "Testing MCP server installation and basic functionality..."
          
          # Test MCP server availability
          npm list -g @executeautomation/playwright-mcp-server
          
          # Test Playwright installation
          npx playwright --version
          
          echo "✅ MCP server health check passed"

  mcp_integration_tests:
    name: 🤖 MCP Integration Tests
    needs: mcp_server_health
    runs-on: ubuntu-latest
    
    steps:
      - name: 📁 Checkout Repository
        uses: actions/checkout@v4
      
      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      
      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: 🎭 Install Dependencies
        run: |
          npm install -g @executeautomation/playwright-mcp-server
          pip install -r automation_framework/requirements.txt
          playwright install chromium firefox webkit
      
      - name: 🧪 Test MCP Session Management
        run: |
          cd automation_framework
          python -c "
          from mcp_integration import PlaywrightMCPIntegration
          from utils.logger import Logger
          import json
          
          logger = Logger('MCP_Session_Test')
          mcp = PlaywrightMCPIntegration()
          
          # Test 1: Session lifecycle
          logger.info('Testing session lifecycle...')
          success = mcp.start_recording_session('session_test')
          assert success, 'Failed to start session'
          
          session_info = mcp.get_session_info()
          assert session_info['active'], 'Session not active'
          
          summary = mcp.end_recording_session()
          assert summary['status'] == 'completed', 'Session did not complete'
          
          logger.info('✅ Session lifecycle test passed')
          
          # Test 2: Action recording
          logger.info('Testing action recording...')
          mcp.start_recording_session('action_test')
          
          mcp.record_action('navigate', value='https://www.saucedemo.com')
          mcp.record_action('fill', selector='[data-test=\"username\"]', value='test_user')
          mcp.record_action('click', selector='[data-test=\"login-button\"]')
          mcp.record_action('assert_visible', selector='.inventory_list')
          
          session_info = mcp.get_session_info()
          assert session_info['actions_count'] == 4, f'Expected 4 actions, got {session_info[\"actions_count\"]}'
          
          summary = mcp.end_recording_session()
          logger.info(f'✅ Action recording test passed: {summary}')
          
          print('All MCP session tests completed successfully!')
          "
      
      - name: 🔧 Test Code Generation
        run: |
          cd automation_framework
          python -c "
          from mcp_integration import PlaywrightMCPIntegration
          from utils.logger import Logger
          
          logger = Logger('MCP_CodeGen_Test')
          mcp = PlaywrightMCPIntegration()
          
          # Start session and record actions
          mcp.start_recording_session('codegen_test')
          
          # Record a complete test scenario
          mcp.record_action('navigate', value='https://www.saucedemo.com')
          mcp.record_action('fill', selector='[data-test=\"username\"]', value='standard_user')
          mcp.record_action('fill', selector='[data-test=\"password\"]', value='secret_sauce')
          mcp.record_action('click', selector='[data-test=\"login-button\"]')
          mcp.record_action('assert_visible', selector='.inventory_list')
          mcp.record_action('click', selector='[data-test=\"add-to-cart-sauce-labs-backpack\"]')
          mcp.record_action('assert_text', selector='.shopping_cart_badge', value='1')
          
          # Test Python code generation
          python_code = mcp.generate_test_code('python')
          assert python_code, 'Failed to generate Python code'
          assert 'def test_' in python_code, 'Python code missing test function'
          assert 'page.goto' in python_code, 'Python code missing navigation'
          
          # Test TypeScript code generation
          typescript_code = mcp.generate_test_code('typescript')
          assert typescript_code, 'Failed to generate TypeScript code'
          assert 'test(' in typescript_code, 'TypeScript code missing test function'
          assert 'page.goto' in typescript_code, 'TypeScript code missing navigation'
          
          # Save generated tests
          python_file = mcp.save_generated_test(python_code, 'python')
          typescript_file = mcp.save_generated_test(typescript_code, 'typescript')
          
          assert python_file, 'Failed to save Python test'
          assert typescript_file, 'Failed to save TypeScript test'
          
          mcp.end_recording_session()
          
          logger.info('✅ Code generation test passed')
          print(f'Generated files: {python_file}, {typescript_file}')
          "
      
      - name: 🏃 Test MCP Runner
        run: |
          cd automation_framework
          python -c "
          from playwright_mcp_runner import PlaywrightMCPRunner
          from utils.logger import Logger
          
          logger = Logger('MCP_Runner_Test')
          runner = PlaywrightMCPRunner()
          
          # Test listing generated tests
          tests = runner.list_generated_tests()
          logger.info(f'Found {len(tests)} generated tests: {[t[\"name\"] for t in tests]}')
          
          # Test cleanup functionality
          cleanup_result = runner.cleanup_generated_tests(older_than_days=0)
          logger.info(f'Cleanup result: {cleanup_result}')
          
          logger.info('✅ MCP runner test passed')
          "
      
      - name: 🔄 Test Cross-Browser Code Generation
        if: github.event.inputs.test_mode != 'quick'
        run: |
          cd automation_framework
          python -c "
          from mcp_integration import PlaywrightMCPIntegration
          from utils.logger import Logger
          
          logger = Logger('MCP_CrossBrowser_Test')
          browsers = ['chromium', 'firefox', 'webkit']
          
          for browser in browsers:
              logger.info(f'Testing code generation for {browser}...')
              
              mcp = PlaywrightMCPIntegration()
              mcp.start_recording_session(f'{browser}_test')
              
              # Record browser-specific actions
              mcp.record_action('navigate', value='https://www.saucedemo.com')
              mcp.record_action('fill', selector='[data-test=\"username\"]', value='standard_user')
              mcp.record_action('click', selector='[data-test=\"login-button\"]')
              
              # Generate and save test
              code = mcp.generate_test_code('python')
              assert code, f'Failed to generate code for {browser}'
              
              file_path = mcp.save_generated_test(code, 'python')
              assert file_path, f'Failed to save test for {browser}'
              
              mcp.end_recording_session()
              logger.info(f'✅ {browser} test generation completed')
          
          print('All cross-browser tests completed successfully!')
          "
      
      - name: 📦 Upload Generated Tests
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mcp-generated-tests
          path: automation_framework/generated_tests/
          retention-days: 7
      
      - name: 📊 Generate MCP Report
        if: always()
        run: |
          cd automation_framework
          python -c "
          import os
          import json
          from datetime import datetime
          from pathlib import Path
          
          # Collect information about generated tests
          generated_dir = Path('generated_tests')
          tests = []
          
          if generated_dir.exists():
              for file in generated_dir.glob('*'):
                  if file.is_file():
                      tests.append({
                          'name': file.name,
                          'size': file.stat().st_size,
                          'language': 'python' if file.suffix == '.py' else 'typescript',
                          'created': datetime.fromtimestamp(file.stat().st_ctime).isoformat()
                      })
          
          report = {
              'timestamp': datetime.now().isoformat(),
              'total_tests_generated': len(tests),
              'tests': tests,
              'mcp_server_status': 'healthy',
              'integration_status': 'successful'
          }
          
          with open('mcp_integration_report.json', 'w') as f:
              json.dump(report, f, indent=2)
          
          print(f'MCP Integration Report: {len(tests)} tests generated')
          "
      
      - name: 📋 Upload MCP Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mcp-integration-report
          path: automation_framework/mcp_integration_report.json
          retention-days: 30

  mcp_performance_test:
    name: ⚡ MCP Performance Test
    needs: mcp_integration_tests
    runs-on: ubuntu-latest
    if: github.event.inputs.test_mode == 'full'
    
    steps:
      - name: 📁 Checkout Repository
        uses: actions/checkout@v4
      
      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: 🎭 Install Dependencies
        run: |
          npm install -g @executeautomation/playwright-mcp-server
          pip install -r automation_framework/requirements.txt
          playwright install chromium
      
      - name: ⚡ Performance Test
        run: |
          cd automation_framework
          python -c "
          from mcp_integration import PlaywrightMCPIntegration
          from utils.logger import Logger
          import time
          
          logger = Logger('MCP_Performance_Test')
          
          # Test 1: Session creation performance
          start_time = time.time()
          mcp = PlaywrightMCPIntegration()
          
          for i in range(10):
              success = mcp.start_recording_session(f'perf_test_{i}')
              assert success, f'Failed to start session {i}'
              mcp.clear_session()
          
          session_time = time.time() - start_time
          logger.info(f'Session creation performance: {session_time:.2f}s for 10 sessions')
          
          # Test 2: Action recording performance
          start_time = time.time()
          mcp.start_recording_session('action_perf_test')
          
          for i in range(100):
              mcp.record_action('click', selector=f'button_{i}', value=f'test_{i}')
          
          action_time = time.time() - start_time
          logger.info(f'Action recording performance: {action_time:.2f}s for 100 actions')
          
          # Test 3: Code generation performance
          start_time = time.time()
          python_code = mcp.generate_test_code('python')
          typescript_code = mcp.generate_test_code('typescript')
          
          codegen_time = time.time() - start_time
          logger.info(f'Code generation performance: {codegen_time:.2f}s for 2 languages')
          
          mcp.end_recording_session()
          
          # Performance thresholds
          assert session_time < 5.0, f'Session creation too slow: {session_time}s'
          assert action_time < 2.0, f'Action recording too slow: {action_time}s'
          assert codegen_time < 3.0, f'Code generation too slow: {codegen_time}s'
          
          logger.info('✅ All performance tests passed')
          
          print(f'''
          Performance Test Results:
          - Session Creation: {session_time:.2f}s (< 5.0s ✅)
          - Action Recording: {action_time:.2f}s (< 2.0s ✅)  
          - Code Generation: {codegen_time:.2f}s (< 3.0s ✅)
          ''')
          "

  notify_mcp_results:
    name: 📢 Notify MCP Results
    needs: [mcp_server_health, mcp_integration_tests, mcp_performance_test]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: 📊 Determine Status
        id: status
        run: |
          if [[ "${{ needs.mcp_server_health.result }}" == "success" && 
                "${{ needs.mcp_integration_tests.result }}" == "success" && 
                ("${{ needs.mcp_performance_test.result }}" == "success" || "${{ needs.mcp_performance_test.result }}" == "skipped") ]]; then
            echo "status=success" >> $GITHUB_OUTPUT
            echo "emoji=✅" >> $GITHUB_OUTPUT
            echo "color=good" >> $GITHUB_OUTPUT
          else
            echo "status=failure" >> $GITHUB_OUTPUT
            echo "emoji=❌" >> $GITHUB_OUTPUT
            echo "color=danger" >> $GITHUB_OUTPUT
          fi
      
      - name: 📋 Create Summary
        run: |
          cat >> $GITHUB_STEP_SUMMARY << EOF
          # 🤖 MCP Integration Pipeline Summary
          
          ## Status: ${{ steps.status.outputs.emoji }} ${{ steps.status.outputs.status }}
          
          **Test Results:**
          - **MCP Server Health**: ${{ needs.mcp_server_health.result }}
          - **Integration Tests**: ${{ needs.mcp_integration_tests.result }}
          - **Performance Tests**: ${{ needs.mcp_performance_test.result }}
          
          **Run Information:**
          - **Trigger**: ${{ github.event_name }}
          - **Test Mode**: ${{ github.event.inputs.test_mode || 'full' }}
          - **Run Number**: #${{ github.run_number }}
          
          **Features Tested:**
          - ✅ MCP server installation and health
          - ✅ Session lifecycle management
          - ✅ Action recording capabilities
          - ✅ Code generation (Python & TypeScript)
          - ✅ Cross-browser compatibility
          - ✅ Performance benchmarks
          
          ---
          *MCP Integration powered by Playwright MCP Server*
          EOF
